export default {
  bits: [1, 0, 1, 0],
  Fs: 2048,
  encType: 'hamm',
  Fa: 8,
  modType: 'bpsk',
  impType: 'awgn',
  impPower: 1,
  cutoff: 8,
  taps: 200,
  waveshape: 'sine',
  allWaveshapes: ['sine', 'square', 'triangular'],
  allFs: [128, 256, 512, 1024, 2048],
  allFa: [1, 2, 4, 8, 16, 32],
  allEnc: ['hamming'],
  encLength: 8,
  apps: ['simulator', 'spectrometer'],
  appIndex: 0,
  graph: { t: { x: [0], y: [0] }, f: { x: [0], y: [0] } },
};
